<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE participantList [
  <!ELEMENT participantList (Participant+)>
  <!ELEMENT Participant (Game)>
  <!ATTLIST Participant Participant_id ID #REQUIRED>
  <!ATTLIST Game Game_id ID #REQUIRED>
  <!ELEMENT Game (#PCDATA)>
]>

<root>
<!-- Comment -->
<participantList>
  <?refreshData targetID="t17"?>
  <Participant Participant_id="1" PersonName="Juhamatti Tapio Aaltonen" Sex="M" Age="28" WeightP="85" HeightP="184" Team="Finland">
    <Game Game_id="1" YearG="2014" Season="Winter" City="Sochi"/>
    <Game Game_id="53" YearG="3014" Season="Winter" City="Sochi"/>
  </Participant>
  <Participant Participant_id="2" PersonName="Paavo Johannes Aaltonen" Sex="M" Age="32" WeightP="64" HeightP="175" Team="Finland">
    <Game Game_id="2" YearG="1948" Season="Summer" City="London"/>
    <Game Game_id="3" YearG="1952" Season="Summer" City="Helsinki"/>
    <Game Game_id="54" YearG="2948" Season="Summer" City="London"/>
    <Game Game_id="55" YearG="2952" Season="Summer" City="Helsinki"/>
  </Participant>
  <Participant Participant_id="3" PersonName="Kjetil Andr Aamodt" Sex="M" Age="34" WeightP="85" HeightP="176" Team="Norway">
    <Game Game_id="4" YearG="1992" Season="Winter" City="Albertville"/>
    <Game Game_id="5" YearG="1994" Season="Winter" City="Lillehammer"/>
    <Game Game_id="6" YearG="2002" Season="Winter" City="Salt Lake City"/>
    <Game Game_id="7" YearG="2006" Season="Winter" City="Torino"/>
    <Game Game_id="56" YearG="2992" Season="Winter" City="Albertville"/>
    <Game Game_id="57" YearG="2994" Season="Winter" City="Lillehammer"/>
    <Game Game_id="58" YearG="3002" Season="Winter" City="Salt Lake City"/>
    <Game Game_id="59" YearG="3006" Season="Winter" City="Torino"/>
  </Participant>
  <Participant Participant_id="4" PersonName="Pepijn Aardewijn" Sex="M" Age="26" WeightP="72" HeightP="189" Team="Netherlands">
    <Game Game_id="8" YearG="1996" Season="Summer" City="Atlanta"/>
    <Game Game_id="60" YearG="2996" Season="Summer" City="Atlanta"/>
  </Participant>
  <Participant Participant_id="5" PersonName="Ann Kristin Aarnes" Sex="F" Age="23" WeightP="64" HeightP="182" Team="Norway">
    <Game Game_id="8" YearG="1996" Season="Summer" City="Atlanta"/>
    <Game Game_id="60" YearG="2996" Season="Summer" City="Atlanta"/>
  </Participant>
  <Participant Participant_id="6" PersonName="Giovanni Abagnale" Sex="M" Age="21" WeightP="90" HeightP="198" Team="Italy">
    <Game Game_id="9" YearG="2016" Season="Summer" City="Rio de Janeiro"/>
    <Game Game_id="61" YearG="3016" Season="Summer" City="Rio de Janeiro"/>
  </Participant>
  <Participant Participant_id="7" PersonName="Jos Luis Abajo Gmez" Sex="M" Age="30" WeightP="87" HeightP="194" Team="Spain">
    <Game Game_id="10" YearG="2008" Season="Summer" City="Beijing"/>
    <Game Game_id="62" YearG="3008" Season="Summer" City="Beijing"/>
  </Participant>
  <Participant Participant_id="8" PersonName="Patimat Abakarova" Sex="F" Age="21" WeightP="49" HeightP="165" Team="Azerbaijan">
    <Game Game_id="9" YearG="2016" Season="Summer" City="Rio de Janeiro"/>
    <Game Game_id="61" YearG="3016" Season="Summer" City="Rio de Janeiro"/>
  </Participant>
  <Participant Participant_id="9" PersonName="Mariya Vasilyevna Abakumova (-Tarabina)" Sex="F" Age="22" WeightP="80" HeightP="179" Team="Russia">
    <Game Game_id="10" YearG="2008" Season="Summer" City="Beijing"/>
    <Game Game_id="62" YearG="3008" Season="Summer" City="Beijing"/>
  </Participant>
  <Participant Participant_id="10" PersonName="Aleksey Aleksandrovich Abalmasov" Sex="M" Age="28" WeightP="83" HeightP="180" Team="Belarus">
    <Game Game_id="10" YearG="2008" Season="Summer" City="Beijing"/>
    <Game Game_id="62" YearG="3008" Season="Summer" City="Beijing"/>
  </Participant>
  <Participant Participant_id="11" PersonName="Luc Abalo" Sex="M" Age="31" WeightP="86" HeightP="182" Team="France">
    <Game Game_id="9" YearG="2016" Season="Summer" City="Rio de Janeiro"/>
    <Game Game_id="10" YearG="2008" Season="Summer" City="Beijing"/>
    <Game Game_id="11" YearG="2012" Season="Summer" City="London"/>
    <Game Game_id="61" YearG="3016" Season="Summer" City="Rio de Janeiro"/>
    <Game Game_id="62" YearG="3008" Season="Summer" City="Beijing"/>
    <Game Game_id="63" YearG="3012" Season="Summer" City="London"/>
  </Participant>
  <Participant Participant_id="12" PersonName="Jouan Patrice Abanda Etong" Sex="M" Age="22" WeightP="82" HeightP="185" Team="Cameroon">
    <Game Game_id="12" YearG="2000" Season="Summer" City="Sydney"/>
    <Game Game_id="64" YearG="3000" Season="Summer" City="Sydney"/>
  </Participant>
  <Participant Participant_id="13" PersonName="Jos Mara Abarca Plotas" Sex="M" Age="22" WeightP="83" HeightP="186" Team="Spain">
    <Game Game_id="8" YearG="1996" Season="Summer" City="Atlanta"/>
    <Game Game_id="60" YearG="2996" Season="Summer" City="Atlanta"/>
  </Participant>
  <Participant Participant_id="14" PersonName="Stephen Anthony Abas" Sex="M" Age="26" WeightP="55" HeightP="165" Team="United States">
    <Game Game_id="13" YearG="2004" Season="Summer" City="Athina"/>
    <Game Game_id="65" YearG="3004" Season="Summer" City="Athina"/>
  </Participant>
  <Participant Participant_id="15" PersonName="Alejandro Abascal Garca" Sex="M" Age="28" WeightP="82" HeightP="181" Team="Spain">
    <Game Game_id="14" YearG="1980" Season="Summer" City="Moskva"/>
    <Game Game_id="66" YearG="2980" Season="Summer" City="Moskva"/>
  </Participant>
  <Participant Participant_id="16" PersonName="Jos Manuel Abascal Gmez" Sex="M" Age="26" WeightP="67" HeightP="182" Team="Spain">
    <Game Game_id="15" YearG="1984" Season="Summer" City="Los Angeles"/>
    <Game Game_id="67" YearG="2984" Season="Summer" City="Los Angeles"/>
  </Participant>
  <Participant Participant_id="17" PersonName="Tamila Rashidovna Abasova" Sex="F" Age="21" WeightP="60" HeightP="163" Team="Russia">
    <Game Game_id="13" YearG="2004" Season="Summer" City="Athina"/>
    <Game Game_id="65" YearG="3004" Season="Summer" City="Athina"/>
  </Participant>
  <Participant Participant_id="18" PersonName="Jol Marc Abati" Sex="M" Age="38" WeightP="85" HeightP="190" Team="France">
    <Game Game_id="10" YearG="2008" Season="Summer" City="Beijing"/>
    <Game Game_id="62" YearG="3008" Season="Summer" City="Beijing"/>
  </Participant>
  <Participant Participant_id="19" PersonName="Pter Abay" Sex="M" Age="30" WeightP="79" HeightP="181" Team="Hungary">
    <Game Game_id="16" YearG="1992" Season="Summer" City="Barcelona"/>
    <Game Game_id="68" YearG="2992" Season="Summer" City="Barcelona"/>
  </Participant>
  </participantList>
  </root>